site_name: BaseX Documentation
theme: readthedocs
repo_url: https://github.com/dirkk/basex-rtd
site_favicon: favicon.ico
markdown_extensions: [admonition, extra]
include_search: true
pages:
- ["index.md", "Getting Started", "Main Page"]
- ["Getting Started.md", "Getting Started", "Getting Started"]
- ["Startup.md", "Getting Started", "Startup"]
- ["Command-Line Options.md", "Getting Started", "Command-Line Options"]
- ["Databases.md", "Getting Started", "Databases"]
- ["Commands.md", "Getting Started", "Commands"]
- ["DBA.md", "Getting Started", "DBA"]
- ["Database Server.md", "Getting Started", "Database Server"]
- ["Graphical User Interface.md", "Getting Started", "Graphical User Interface"]
- ["Parsers.md", "Getting Started", "Parsers"]
- ["Standalone Mode.md", "Getting Started", "Standalone Mode"]
- ["Start Scripts.md", "Getting Started", "Start Scripts"]
- ["Options.md", "Getting Started", "Options"]
- ["WebDAV.md", "WebDAV", "WebDAV"]
- ["WebDAV: GNOME.md", "WebDAV", "WebDAV: GNOME"]
- ["WebDAV: KDE.md", "WebDAV", "WebDAV: KDE"]
- ["WebDAV: Mac OSX.md", "WebDAV", "WebDAV: Mac OSX"]
- ["WebDAV: Windows 7.md", "WebDAV", "WebDAV: Windows 7"]
- ["WebDAV: Windows XP.md", "WebDAV", "WebDAV: Windows XP"]
- ["Module Library.md", "Modules", "Module Library"]
- ["Admin Module.md", "Modules", "Admin Module"]
- ["Archive Module.md", "Modules", "Archive Module"]
- ["Array Module.md", "Modules", "Array Module"]
- ["Binary Module.md", "Modules", "Binary Module"]
- ["CSV Module.md", "Modules", "CSV Module"]
- ["Client Module.md", "Modules", "Client Module"]
- ["Conversion Module.md", "Modules", "Conversion Module"]
- ["Cryptographic Module.md", "Modules", "Cryptographic Module"]
- ["Database Module.md", "Modules", "Database Module"]
- ["Fetch Module.md", "Modules", "Fetch Module"]
- ["File Module.md", "Modules", "File Module"]
- ["Full-Text Module.md", "Modules", "Full-Text Module"]
- ["HTML Module.md", "Modules", "HTML Module"]
- ["HTTP Module.md", "Modules", "HTTP Module"]
- ["Hashing Module.md", "Modules", "Hashing Module"]
- ["Higher-Order Functions Module.md", "Modules", "Higher-Order Functions Module"]
- ["Index Module.md", "Modules", "Index Module"]
- ["Inspection Module.md", "Modules", "Inspection Module"]
- ["JSON Module.md", "Modules", "JSON Module"]
- ["Map Module.md", "Modules", "Map Module"]
- ["Math Module.md", "Modules", "Math Module"]
- ["Output Module.md", "Modules", "Output Module"]
- ["Process Module.md", "Modules", "Process Module"]
- ["Profiling Module.md", "Modules", "Profiling Module"]
- ["RESTXQ Module.md", "Modules", "RESTXQ Module"]
- ["Random Module.md", "Modules", "Random Module"]
- ["Repository Module.md", "Modules", "Repository Module"]
- ["Request Module.md", "Modules", "Request Module"]
- ["SQL Module.md", "Modules", "SQL Module"]
- ["Session Module.md", "Modules", "Session Module"]
- ["Sessions Module.md", "Modules", "Sessions Module"]
- ["Streaming Module.md", "Modules", "Streaming Module"]
- ["Unit Module.md", "Modules", "Unit Module"]
- ["User Module.md", "Modules", "User Module"]
- ["Validation Module.md", "Modules", "Validation Module"]
- ["XQuery Module.md", "Modules", "XQuery Module"]
- ["XSLT Module.md", "Modules", "XSLT Module"]
- ["ZIP Module.md", "Modules", "ZIP Module"]
- ["Geo Module.md", "Modules", "Geo Module"]
- ["Clients.md", "Developer", "Clients"]
- ["Contribute.md", "Developer", "Contribute"]
- ["Developing.md", "Developer", "Developing"]
- ["Developing with Eclipse.md", "Developer", "Developing with Eclipse"]
- ["Java Examples.md", "Developer", "Java Examples"]
- ["Java Bindings.md", "Developer", "Java Bindings"]
- ["Maven.md", "Developer", "Maven"]
- ["Query Mode.md", "Developer", "Query Mode"]
- ["REST.md", "Developer", "REST"]
- ["REST: POST Schema.md", "Developer", "REST: POST Schema"]
- ["RESTXQ.md", "Developer", "RESTXQ"]
- ["Server Protocol.md", "Developer", "Server Protocol"]
- ["Server Protocol: Types.md", "Developer", "Server Protocol: Types"]
- ["Standard Mode.md", "Developer", "Standard Mode"]
- ["Web Application.md", "Developer", "Web Application"]
- ["Android.md", "Developer", "Android"]
- ["Git.md", "Developer", "Git"]
- ["Translations.md", "Developer", "Translations"]
- ["Open Issues.md", "Developer", "Open Issues"]
- ["Releases.md", "Developer", "Releases"]
- ["Integrating Eclipse.md", "Developer", "Integrating Eclipse"]
- ["Integrating oXygen.md", "Developer", "Integrating oXygen"]
- ["Binary Data.md", "Developer", "Binary Data"]
- ["Community:Information.md", "DELETE", "Community:Information"]
- ["Temp.md", "DELETE", "Temp"]
- ["Documentation.md", "DELETE", "Documentation"]
- ["Security: Use Cases.md", "DELETE", "Security: Use Cases"]
- ["XQuery.md", "XQuery", "XQuery"]
- ["XQuery Recipes.md", "XQuery", "XQuery Recipes"]
- ["XQuery Errors.md", "XQuery", "XQuery Errors"]
- ["XQuery 3.0.md", "XQuery", "XQuery 3.0"]
- ["XQuery 3.1.md", "XQuery", "XQuery 3.1"]
- ["XQuery Update.md", "XQuery", "XQuery Update"]
- ["XForms.md", "XQuery", "XForms"]
- ["Full-Text.md", "XQuery", "Full-Text"]
- ["Higher-Order Functions.md", "XQuery", "Higher-Order Functions"]
- ["Serialization.md", "XQuery", "Serialization"]
- ["Advanced User's Guide.md", "Internals", "Advanced User's Guide"]
- ["Backups.md", "Internals", "Backups"]
- ["Catalog Resolver.md", "Internals", "Catalog Resolver"]
- ["Configuration.md", "Internals", "Configuration"]
- ["Execution Plan.md", "Internals", "Execution Plan"]
- ["Index File Structure.md", "Internals", "Index File Structure"]
- ["Indexes.md", "Internals", "Indexes"]
- ["Logging.md", "Internals", "Logging"]
- ["Statistics.md", "Internals", "Statistics"]
- ["Storage Layout.md", "Internals", "Storage Layout"]
- ["Transaction Management.md", "Internals", "Transaction Management"]
- ["Twitter.md", "Internals", "Twitter"]
- ["User Management.md", "Internals", "User Management"]
- ["Repository.md", "Internals", "Repository"]
- ["Node Storage.md", "Internals", "Node Storage"]
- ["Events.md", "Internals", "Events"]
- ["Shortcuts.md", "Internals", "Shortcuts"]
